-- Link Supabase Auth user_id to analytics devices
--
-- Problem: analytics_devices.user_id is a random UUID generated by register-analytics,
-- completely unrelated to Supabase auth.uid(). This makes it impossible to correlate
-- analytics events with storage/RLS-scoped data.
--
-- Solution: add auth_user_id column so the iOS app can pass its Supabase auth.uid()
-- during registration. For existing devices, track-event lazily backfills via header.

ALTER TABLE analytics_devices ADD COLUMN IF NOT EXISTS auth_user_id TEXT;

-- Index for lookups by auth user (dashboard queries, future JOIN with storage/dreams)
CREATE INDEX IF NOT EXISTS idx_analytics_devices_auth_user_id
  ON analytics_devices (auth_user_id)
  WHERE auth_user_id IS NOT NULL;
